image: debian:bookworm

before_script:
    - ./.github/scripts/prepare-env.sh

format:
    script:
        - mkdir build && cd build
        - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DADD_GRABTHECAM_FARSHOW_DEMO=ON ../
        - make format
        - test -z "$(git diff)" && exit 0 || exit 1

example-build:
    script:
        - mkdir build && cd build
        - cmake -DADD_GRABTHECAM_FARSHOW_DEMO=ON ../
        - make && make install
        - cd ../tests/example-build
        - cp ../../src/example.cpp example.cpp
        - mkdir build && cd build
        - cmake ../
        - make
