image: debian:bookworm

before_script:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y
    cmake
    make
    g++-12
    libopencv-dev
    rapidjson-dev
    libv4l-dev
    clang-tidy
    clang-format

stages:
  - lint
  - export-test

format:
  stage: lint
  script:
    - export CC=/usr/bin/gcc-12 CXX=/usr/bin/g++-12
    - mkdir build && cd build
    - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../
    - make
    - make format

example-build:
  stage: export-test
  script:
    - export CC=/usr/bin/gcc-12 CXX=/usr/bin/g++-12
    - mkdir build && cd build
    - cmake ../
    - make && make install
    - cd ../tests/example-build
    - cp ../../src/example.cpp example.cpp
    - mkdir build && cd build
    - cmake ../
    - make
