name: grabthecam build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CC: /usr/bin/gcc-12
  CXX: /usr/bin/g++-12

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        .github/scripts/prepare-env.sh

    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DADD_GRABTHECAM_FARSHOW_DEMO=ON ..
        make

    - name: Code linting
      run: |
        cd build
        make format
        test -z $(git diff) && exit 0 || exit 1

  example-build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        .github/scripts/prepare-env.sh

    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Install the project
      run: |
        cd build
        make install

    - name: Build the 'example-build'
      run: |
        cd tests/example-build
        cp ../../src/example.cpp ./
        mkdir build
        cd build
        cmake ..
        make
